resume: true
test_only: false
num_workers: 32

required_devices: 8
no_test: false
debug: false
log2tb: true
allow_double_bs: false
seed: 0
distributed: false
test_freq: 1
print_freq: 100

dataset:
  name: "kinetics"
  full_res: true
  batch_size: 256
  video_clip_duration: 0.5
  video_fps: 16.
  crop_size: 224
  audio_clip_duration: 2.
  audio_fps: 24000.
  spectrogram_fps: 100.
  n_fft: 512
  transforms: "msc+color"
  train:
    split: "train"
    use_augmentation: true
    drop_last: true
    clips_per_video: 10
  test:
    split: "val"
    use_augmentation: false
    drop_last: true

optimizer:
  name: "adam"
  weight_decay: 0.00001
  num_epochs: 20
  lr:
    name: "multistep"
    base_lr: 0.0002
    gamma: 1.
    milestones: [5, 10, 15, 20]

loss:
  name: "AVID_CMA"
  args:
    checkpoint: "checkpoints/AVID/Kinetics/R2Plus1D/Cross-N1024-NL/checkpoint-ep20.pth.tar"
    momentum: 0.5
    loss_type: 'nce'
    num_positives: 32
    num_negatives: 1024
    num_negatives_within: 64
    xModal: false
    wModal: true
    wModalCoeff: 3.
    resample_freq: 5
    sampling_args:
      type: "consensus"      # consensus, video, audio, union
      pos_k: 128

model:
  name: "NL-NCE-SelfX-N1024-PosW3-SelfConsensus-N64-Top32-Iter5"
  model_dir: "checkpoints/AVID-CMA/Kinetics/R2Plus1D"
  arch: "av_wrapper"
  args:
    checkpoint: "checkpoints/AVID/Kinetics/R2Plus1D/Cross-N1024-NL/checkpoint-ep20.pth.tar"
    proj_dim: 128
    video_backbone: "R2Plus1D"
    video_backbone_args:
      depth: 18
    audio_backbone: "Conv2D"
    audio_backbone_args:
      depth: 10
