required_devices: 1
resume: false

# defaults
no_test: false
test_only: false
debug: false
seed: 0
distributed: false
test_freq: 1
num_workers: 10

benchmark:
  name: "dcase"

dataset:
  n_folds: 1
  name: "dcase"
  batch_size: 32
  clip_duration: 2.
  audio_fps: 24000.
  spectrogram_fps: 100.
  n_fft: 512
  train:
    split: "train"
    mode: "clip"
    clips_per_video: 60
    use_augmentation: true
    use_shuffle: true
    drop_last: false
  test:
    split: "test"
    mode: "clip"
    clips_per_video: 60
    use_augmentation: false
    use_shuffle: false
    drop_last: false
  test_dense:
    split: "test"
    mode: "video"
    clips_per_video: 60
    use_augmentation: false
    use_shuffle: false
    drop_last: false

model:
  name: "lreg_classifier"
  n_classes: 10
  feat_names: ["conv5x", "conv4x", "conv3x", "conv2x"]
  pooling_ops: ["AdaptiveAvgPool2d((4, 4))", "AdaptiveAvgPool2d((6, 6))", "AdaptiveAvgPool2d((8, 8))", "AdaptiveAvgPool2d((12, 12))"]
  C: 1.0
