resume: true
test_only: false
num_workers: 36

required_devices: 8
no_test: false
debug: false
log2tb: true
allow_double_bs: false
seed: 0
distributed: false
test_freq: 1
print_freq: 100

dataset:
  name: "audioset"
  full_res: false
  batch_size: 256
  video_clip_duration: 0.5
  video_fps: 16.
  crop_size: 112
  audio_clip_duration: 2.
  audio_fps: 24000.
  spectrogram_fps: 50.
  n_fft: 256
  transforms: "msc+color"
  train:
    split: "unbalanced_train-100k"
    use_augmentation: true
    drop_last: true
    clips_per_video: 4
  test:
    split: "eval"
    use_augmentation: false
    drop_last: true

optimizer:
  name: "adam"
  weight_decay: 0.00001
  num_epochs: 102
  lr:
    name: "multistep"
    base_lr: 0.0001
    gamma: 0.1
    milestones: [75, ]

model:
  name: "Cross-N1024-NL"
  model_dir: "checkpoints/AVID/Audioset-Small/R2Plus1D"
  arch: "av_wrapper"
  args:
    proj_dim: [512, 512, 128]
    video_backbone: "R2Plus1D_Small"
    video_backbone_args:
      depth: 10
    audio_backbone: "Conv2D_Small"
    audio_backbone_args:
      depth: 10

loss:
  name: "AVID"
  args:
    num_negatives: 1024
    momentum: 0.5
    loss_type: 'nce'
    xModal: true
    wModal: false
    loss_coeff: [1., 0.]