resume: true
num_workers: 32
log2tb: true
seed: 0
print_freq: 100

dataset:
  name: "audioset"
  full_res: false
  batch_size: 224
  video_clip_duration: 0.5
  video_fps: 16.
  crop_size: 112
  audio_clip_duration: 2.
  audio_fps: 24000.
  spectrogram_fps: 50.
  n_fft: 256
  transforms: "msc+color"
  train:
    split: "unbalanced_train-100k"
    use_augmentation: true
    drop_last: true
    clips_per_video: 4
  test:
    split: "eval"
    use_augmentation: false
    drop_last: true

optimizer:
  name: "adam"
  weight_decay: 0.00001
  num_epochs: 75
  lr:
    name: "multistep"
    base_lr: 0.0001
    gamma: 1.
    milestones: [25, 50, 75]

loss:
  name: "AVID_CMA"
  args:
    checkpoint: "checkpoints/AVID/Audioset-Small/R2Plus1D/Cross-N1024-NL/checkpoint-ep75.pth.tar"
    momentum: 0.5
    loss_type: 'nce'
    num_positives: 128
    num_negatives: 1024
    num_negatives_within: 1024
    xModal: false
    wModal: true
    resample_freq: 10
    sampling_args:
      type: "video"      # consensus, video, audio
      pos_k: 128

model:
  name: "NL-NCE-SelfX-N1024-PosW-SelfVideo-N1024-Top128-Iter10"
  model_dir: "checkpoints/AVID-CMA/Audioset-Small/R2Plus1D"
  arch: "av_wrapper"
  args:
    proj_dim: [512, 512, 128]
    checkpoint: "checkpoints/AVID/Audioset-Small/R2Plus1D/Cross-N1024/checkpoint-ep75.pth.tar"
    video_backbone: "R2Plus1D_Small"
    video_backbone_args:
      depth: 10
    audio_backbone: "Conv2D_Small"
    audio_backbone_args:
      depth: 10